version : '3.8'
services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imdb
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - 3306:3306
    volumes:
      - ./imdb.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 15s
      retries: 3
  
  # mongo:
  #   image: mongo:4.4-bionic
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./imdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app-8084:
    image: alexquesada/imperative-quarkus-mysql-novt:0.0.5
    ports:
      - "8084:8084"
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{ "quarkus.datasource.jdbc.url" : "jdbc:mysql://mysql:3306/imdb" }'
      JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
    depends_on:
      mysql:
        condition: service_healthy

  # app-8080:
  #   image: alexquesada/imperative-sb-mysql-novt:0.0.3
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   environment:
  #     SPRING_APPLICATION_JSON: '{ "spring.datasource.url" : "jdbc:mysql://mysql:3306/imdb" }'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     - mysql
