# version : '3.8'
services:
  # mysql:
  #   image: mysql:8.0.32
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: imdb
  #     MYSQL_PASSWORD: password
  #     MYSQL_USER: user
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./imdb.sql:/docker-entrypoint-initdb.d/1.sql
  #   healthcheck:
  #     test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
  #     interval: 10s
  #     timeout: 20s
  #     retries: 3

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   restart: always
  #   volumes:
  #     - ./rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
  #     - ./imdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   ports:
  #     - 27017:27017
  #   command: ["--replSet", "dbrs", "--bind_ip_all"]
  
  mongo:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./imdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app-8086:
    image: alexquesada/imperative-quarkus-mongo-novt:0.0.2
    ports:
      - "8086:8086"
    restart: always
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: 'mongodb://mongo:27017'
      JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
    depends_on:
      - mongo

  # app-8080:
  #   image: alexquesada/imperative-sb-mysql-novt:0.0.3
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   environment:
  #     SPRING_APPLICATION_JSON: '{ "spring.datasource.url" : "jdbc:mysql://mysql:3306/imdb" }'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     - mysql

  # app-8081:
  #   image: alexquesada/reactive-sb-mysql-novt:0.0.5
  #   ports:
  #     - "8081:8081"
  #   restart: always
  #   environment:
  #     SPRING_APPLICATION_JSON: '{ "spring.r2dbc.url" : "r2dbc:pool:mysql://mysql:3306/imdb" }'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # app-8082:
  #   image: alexquesada/imperative-sb-mongo-novt:0.0.1
  #   ports:
  #     - "8082:8082"
  #   restart: always
  #   environment:
  #     SPRING_APPLICATION_JSON: '{ "spring.data.mongodb.host" : "mongo" }'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     - mongo

  # app-8083:
  #   image: alexquesada/reactive-sb-mongo-novt:0.0.1
  #   ports:
  #     - "8083:8083"
  #   restart: always
  #   environment:
  #     SPRING_APPLICATION_JSON: '{ "spring.data.mongodb.host" : "mongo" }'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     - mongo

  # app-8084:
  #   image: alexquesada/imperative-quarkus-mysql-novt:0.0.5
  #   ports:
  #     - "8084:8084"
  #   restart: always
  #   environment:
  #     SPRING_APPLICATION_JSON: '{ "quarkus.datasource.jdbc.url" : "jdbc:mysql://mysql:3306/imdb" }'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # app-8085:
  #   image: alexquesada/reactive-quarkus-mysql-novt:0.0.4
  #   ports:
  #     - "8085:8085"
  #   restart: always
  #   environment:
  #     QUARKUS_DATASOURCE_REACTIVE_URL: 'mysql://mysql:3306/imdb'
  #     JAVA_TOOL_OPTIONS: '-Xms500M -Xmx500M'
  #   depends_on:
  #     mysql:
  #       condition: service_healthy